-- 1. TABLA USUARIO
CREATE TABLE Usuario (
    id VARCHAR2(100) PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(150) NOT NULL
);

-- 2. TABLA FILA
CREATE TABLE Fila (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nombre VARCHAR2(100) NOT NULL,
    categoria VARCHAR2(50) NOT NULL,
    estado VARCHAR2(20) DEFAULT 'ABIERTA',
    tiempoPromedioAtencion NUMBER DEFAULT 5,
    cantidadEnEspera NUMBER DEFAULT 0,
    cantidadAtendidos NUMBER DEFAULT 0,
    idPropietario VARCHAR2(100) NOT NULL
);

-- 3. TABLA TURNO
CREATE TABLE Turno (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigoTurno VARCHAR2(20) DEFAULT 'A-00',
    idFila NUMBER NOT NULL,
    
    idUsuario VARCHAR2(100) NOT NULL,
    
    nombreUsuario VARCHAR2(100),
    correoUsuario VARCHAR2(150),
    
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    estado VARCHAR2(20) DEFAULT 'EN_ESPERA',
    
    -- Llaves foráneas
    CONSTRAINT fk_fila FOREIGN KEY (idFila) REFERENCES Fila(id) ON DELETE CASCADE,
    CONSTRAINT fk_usuario FOREIGN KEY (idUsuario) REFERENCES Usuario(id) ON DELETE CASCADE
);

select * from table(dbms_xplan.display_cursor(sql_id=>'dpmxxqr73d2a6', format=>'ALLSTATS LAST'));
